### ISSUE TITLE
Two projects you might want to check out

### ISSUE THREAD

**Issue by cfuendev** [rozniak/xfce-winxp-tc#137]
Hey! I'm currently using your theme and having a blast, so first of all, I need to thank you for making the nostalgia ricing more accessible to us users by abstracting the development part from us.

I opened this issue just because I wanted to leave some projects here that might help you get ideas on tackling problems or enhancements, in case you didn't know them:

[B00merang Proyect's Windows XP GTK Themes](https://github.com/B00merang-Project/Windows-XP)
[The Download Link](https://www.opendesktop.org/p/1230964/)
They nailed the panel, so it might be helpful.

[ZoomTen's WinXP theme](https://github.com/ZoomTen/xptheme-20180113)
Looks like they themed the Whisker Menu? Which could help with #135, tho the theme is GTK-2-Only.
Apparently it also has a LibreOffice theme, which you might be interested in, specially because of the icons.

**Comment by rozniak** [comment]
Yea I have seen these, I started this project because I wanted 'more'. :stuck_out_tongue: 

> [B00merang Proyect's Windows XP GTK Themes](https://github.com/B00merang-Project/Windows-XP)
> [The Download Link](https://www.opendesktop.org/p/1230964/)
> They nailed the panel, so it might be helpful.

Any particular part that stands out to you? I have some work I need to do on `xfce4-panel` itself and submit upstream for theming to work a bit better. It might be in future that I write the taskbar itself rather than relying on XFCE to be honest.

> [ZoomTen's WinXP theme](https://github.com/ZoomTen/xptheme-20180113)
> Looks like they themed the Whisker Menu? Which could help with https://github.com/rozniak/xfce-winxp-tc/issues/135, tho the theme is GTK-2-Only.

This repo doesn't use the Whisker Menu - there's the Start button plugin instead. For #135 I am adding translations from Windows XP's MUI packs so that the project works for people in other languages. :grin: 

> Apparently it also has a LibreOffice theme, which you might be interested in, specially because of the icons.

I decided I'm not really going to do any application-specific theming, other than to perhaps fix any general styling issues. This project covers the 'generic' stuff in much the same way Windows XP does - I'm leaving per-app things (such as Firefox) up to the user.

The only real exception is icons, but that's only to use an XP-era icon if one exists for the particular application (people have suggested setting Firefox's icon to that of IE6's, or LibreOffice to Office 2003's - I don't feel like pretending programs are something they're not). There *is* a Firefox icon in this repo, it is the icon from Firefox 3.6 as it is era appropriate and goes well with the theme.

**Comment by AliAndalus** [comment]
I like the Windows XP like taskbar from ZoomTen's WinXP theme, the light-blue color from the tray-icons is more realistic.
![taskbar](https://user-images.githubusercontent.com/103277030/165568089-54a04f2c-c702-4efd-bffa-3aee34880a57.png)
.

**Comment by rozniak** [comment]
The light blue colour there in this repo is straight from `Luna.msstyles` itself.

**Comment by AliAndalus** [comment]
Yeah, but I mean, all tray icons inside the light-blue bar, not only the clock.

**Comment by rozniak** [comment]
I would like the notif area icons as well, this stuff takes time though - busy getting some automation together for pulling translations across from MUI sources for that other issue atm.

**Comment by AliAndalus** [comment]
Okay, no problem, thank you :)

**Comment by rozniak** [comment]
Closing as old issue that has been answered
