### ISSUE TITLE
How do you enable the theme?

### ISSUE THREAD

**Issue by Techwizz-somboo** [rozniak/xfce-winxp-tc#142]
Hi,
I built and installed all the deb files but how do I enable it? Do I need to manually adjust it or is there an easier way? 
Thanks
![image](https://user-images.githubusercontent.com/44146804/169679307-36a2de77-ddc4-4377-990f-a890000aa3ef.png)

**Comment by Techwizz-somboo** [comment]
Also after installing the fork of the xfce panel, I no longer have the start menu as an option to add to my panel. I had it before installing the fork and it did work. Any ideas?

**Comment by rozniak** [comment]
> Do I need to manually adjust it or is there an easier way?

It's all done through XFCE settings atm, which is quite spread out. The steps for selecting all the theme parts once installed is listed here: https://github.com/rozniak/xfce-winxp-tc/issues/122 (since at some stage I would like to replace this with a single dialog like the one from XP where you just pick it from a drop down)

> Also after installing the fork of the xfce panel, I no longer have the start menu as an option to add to my panel. I had it before installing the fork and it did work. Any ideas?

Seems like none of the external panel plugins are showing up at all - is this normal Debian 11 with XFCE 4.16 that you installed the fork on?

**Comment by Techwizz-somboo** [comment]
> Seems like none of the external panel plugins are showing up at all - is this normal Debian 11 with XFCE 4.16 that you installed the fork on?

Yes, it is.

**Comment by Techwizz-somboo** [comment]
Opening the panel in debug mode, it seems it's looking for plugins in `/usr/local/share/xfce4/panel/plugins` and not in `/usr/share/xfce4/panel/plugins`

**Comment by Techwizz-somboo** [comment]
Nevermind about the icons, learned you needed to checkout the feat-72 branch. Thanks for your help!
