### ISSUE TITLE
Bitmaps necessary for start menu

### ISSUE THREAD

**Issue by blue-devil-93** [rozniak/xfce-winxp-tc#147]
Hi,

The start menu is especially  nice got it working on xubuntu 22.04.  Ill look at it next days and send you a picture less scss stylesheet for start menu.
(So that it works with Luna 40 or every other adwaita based theme.) .

**Comment by blue-devil-93** [comment]
Done now. it works very well thx!

[_xp-start-plugin.scss.txt](https://github.com/rozniak/xfce-winxp-tc/files/9078636/_xp-start-plugin.scss.txt)

![xp-mate-menu](https://user-images.githubusercontent.com/59343188/178135482-27b3544b-9bb5-40f4-9867-c60d2ef3f973.png)

**Comment by rozniak** [comment]
I am confused, what is this stylesheet meant to do that the existing one doesn't?

**Comment by blue-devil-93** [comment]
The existing one doesn't Work in adwaita or any third Party theme. My Variant ist a bit more compatible since it doesn't use pixmaps that much

**Comment by rozniak** [comment]
> The existing one doesn't Work in adwaita or any third Party theme. My Variant ist a bit more compatible since it doesn't use pixmaps that much

I'm really confused, the Start menu should look fine in Adwaita (and thus, third party themes):
![image](https://user-images.githubusercontent.com/13258281/178363214-29d3433d-95dd-48e4-a792-5ccaf555d865.png)

I intentionally put in some sane defaults in the Start menu itself so that it should work correctly in other themes, but it can also be overridden by themes to style it should they want to (like the themes in this repo).

> If you want i can try to add the block graphic look to luna 40 and make the track-/slider like in your theme just to prove that pixmaps are mostly unecessary nowadays for gtk3 theming. Pixmaps even gets blurry and buggy once you activate dpi scaling etc. .

There isn't really a perfect solution for it. In some spots I replaced with gradients in areas where the UI is expected to vary in size and gradients alone achieve an accurate result (eg. the taskbar buttons), but some are left as images (such as sliders, check boxes etc.). I purposefully used images because they provided better accuracy at the default DPI.

DPI scaling in general is pretty shoddy and GTK does a terrible job with scaling - personally I see it as a GTK flaw and imo it's pointless to try and work around it because the compromises would make the theme too inaccurate.

**Comment by blue-devil-93** [comment]
Have done some more Research:  it doesn't work well once you use a menubar
gradient or special menuitem gradient. Also toolbar Buttons maybe Buggy
depending on themes so an example overriding every Thing ist good for theme
devs.

Candy i'll Post soon Here.

**Comment by rozniak** [comment]
Are you just copying the Start menu SCSS from the Luna theme in here? If so there's no surprise it is buggy, because it was never intended to be mixed and matched with other themes - all the proportions and styles are defined under the expectation that it is transpiled with the rest of the Luna theme, not bodged in with something else.

Recolouring will be a pain for now until the work on the `feat-13` branch is complete. The work I did so far was just to get a theme working, it has a lot of refactoring to be done which most likely would help with your recolouring.

**Comment by blue-devil-93** [comment]
[Candy-files-code.zip](https://github.com/rozniak/xfce-winxp-tc/files/9093694/Candy-files-code.zip)
Here are some sources. Cionatins another menu scss. 
Of course. And it won`t work since it requires to many pictures. Now i did put some gradient as placeholder and voila it works.

![Candy](https://user-images.githubusercontent.com/59343188/178509216-343fde40-91a9-4c47-bf24-d6b68c4b7d62.png)
![Candy-234](https://user-images.githubusercontent.com/59343188/178509239-ebd79f12-42e2-41c1-b6cd-fb9cd2fbf4af.png)
 It is very difficult to reconstruct Candy but maybe my approach helps you a bit.
 Im very unsure about how trackbars-/scale slider  and panel buttons looked. Maybe they looked like this:?
![Millennium](https://user-images.githubusercontent.com/59343188/178510266-cd5fb6a1-c2e6-466b-b219-ced3999c5f27.png)

**Comment by rozniak** [comment]
It's cool to see your themes for the Start menu. Hopefully when I get back on `feat-13` once that's done it should be far easier to create derivative themes because I plan on separating the theme colours/images out from the general structure (so there's a common base theme structure, and then the colours etc. are added on top).

**Comment by blue-devil-93** [comment]
@Rory Fewell
You use the same Folder structure method as the author of B00merang
theming.  Personally i use  meld and sublime text. My workflow is to keep
the changes as minimal as possible and i do most times first create a draft
code base theme. This theme is a modded adwaita.
Then  i do lets say  Luna style  and then copy the entire luna gtk3 Folder
rename it aero and apply everything so that it looks like aero etc. In the
end result is very similar. Just the way ita done is another.

 The newest gtk4adwaita is more like the theme devellopment Kit from
B00merang. Tried to port it to gtk4 but the new adwaita requires a
different technique. At the moment i dont have the time to provide evry
theme for gtk4.6 etc. Also you need to recompile whole adwaita to publish a
very tiresome work.

 But gtk3 works like a charm.

**Comment by blue-devil-93** [comment]
![dark-theme](https://user-images.githubusercontent.com/59343188/179900258-90734614-6134-41bb-a22d-931c6cf36692.png)
[_xp-start-plugin-dsark.scss.txt](https://github.com/rozniak/xfce-winxp-tc/files/9146632/_xp-start-plugin-dsark.scss.txt)
Another variant. Tried to make it even more gradient like but my nvidia graphic card driver is buggy. Thats why i didn`t style it more. Need to test bitmaps for this style. 

GTK4 itself is changing very fast atm. Too fast to do anything serious with it.Wrote with gnome devs - Therming on gtk4 is not supported . Theyll tell you its impossible- did check it myself and that claim is somewhat false. However  hacking an unstable Toolkit is pointless.

**Comment by rozniak** [comment]
> ![dark-theme](https://user-images.githubusercontent.com/59343188/179900258-90734614-6134-41bb-a22d-931c6cf36692.png)
> [_xp-start-plugin-dsark.scss.txt](https://github.com/rozniak/xfce-winxp-tc/files/9146632/_xp-start-plugin-dsark.scss.txt)
> Another variant. Tried to make it even more gradient like but my nvidia graphic card driver is buggy. Thats why i didn`t style it more. Need to test bitmaps for this style.

This is excellent work mate!

BTW in future I also want to implement vertical username on the Start menu, mainly for the Professional theme as seen in this screenshot:
![whistler](https://betawiki.net/images/b/b3/WindowsXP-5.1.2276-Start.png)

Might use a GTK3 style property or something for it. Unfortunately not available in GTK4 but I'm not fussed about that really I guess.

**Comment by blue-devil-93** [comment]
Have,
you the msstyle for this resource?
Professional seems nice.

If i recall correctly this look can technically  be implemeted with the
current menu code already using some css hacks. padding and border image or
inset I'll look and post about it here next day(s)

**Comment by rozniak** [comment]
> Have, you the msstyle for this resource? Professional seems nice.

Not to hand, you can grab it from a copy of Whistler build 2276. There are multiple iterations of the Professional/Watercolor theme. The work in `feat-13` has a Start button based off of 2419.



> If i recall correctly this look can technically be implemeted with the current menu code already using some css hacks. padding and border image or inset I'll look and post about it here next day(s)

AFAIK GTK3 does not implement any text orientation properties that would allow for the vertical text, that's the only complicated bit that might need implementing in code.

**Comment by blue-devil-93** [comment]
Found watercolor as windowblinds. Then i can rather quickly load it into
gtk2. There was even a library (metathemes if i recall correctly) that
could load xp msstyles to an early gtk2 version.

Watercolor43.exe which should be the second build of watercolor 24? you
mentioned.And  gtk3 is doable too.

**Comment by rozniak** [comment]
> There was even a library (metathemes if i recall correctly) that could load xp msstyles to an early gtk2 version.

Maybe a pipe-dream, would love to get a similar thing working with GTK3 in this repo. I don't expect it will be perfect but it would be cool to try out. :grin:

**Comment by blue-devil-93** [comment]
![grafik](https://user-images.githubusercontent.com/59343188/180382108-d27f6f87-3e95-4547-8092-38be60c2e715.png)

**Comment by rozniak** [comment]
Do you have high DPI on? Looks very padded out.

**Comment by blue-devil-93** [comment]
![mate-menu-padding](https://user-images.githubusercontent.com/59343188/180590260-49150bcf-76da-4f71-98fa-2de610a50cf2.png)

hope its better now. Is there a way to change apps in favourite applications secdtion?

**Comment by rozniak** [comment]
> Is there a way to change apps in favourite applications secdtion?

Not yet, it simply displays the first 6 items when sorted alphabetically. There is an open issue #58 to add weighting akin to XP.

**Comment by blue-devil-93** [comment]
Ok, but its fine like that. Maybe think of a mechanism the user can select which apps to choose. 

Send you something to oddmatics email i found in control file of deb . Maybe it helps with your project.

**Comment by rozniak** [comment]
> Maybe think of a mechanism the user can select which apps to choose.

Would you be happy with Start menu pins like XP has?

> Send you something to oddmatics email i found in control file of deb . Maybe it helps with your project.

I have seen, thanks! I will check it out when I get some time. :grin:

**Comment by blue-devil-93** [comment]
Pinning some applications to favourite menu is the best alternative if a real start ed applications  usage analyzer like in xp is to much to implement. 

Thx. Just write me if it works once you have time. Progressed a bit further today, color conversion is soon stable. Image selector has some quirks , however its working mostly.Protoype for parsing the  rendering and slicing options  of images is in  progress.

**Comment by rozniak** [comment]
> if a real start ed applications usage analyzer like in xp is to much to implement.

That's what that issue is for, obviously I don't have the exact algorithm Windows XP uses, but I will be implementing a system of weighting programs based on how often you launch them (prioritising recent activity of course).

**Comment by rozniak** [comment]
As part of #13 I will probably add some little things for the Start menu to make using of your `font-size: 0pt` trick. Just making a note here of what stuff I need to do:

- Start menu button, should have two labels for `Start` and `start`, and the theme can use `font-size: 0pt` to hide the appropriate label (so Windows Classic would hide `start`, and Luna would hide `Start`)
- Vertical / horizontal username on Start menu - similar deal, have both in the widget tree and allow the theme to hide whichever one using `font-size: 0pt` (needed for Professional / Watercolor)
- Also relevant for the above... might need to make it possible to hide the user picture for the vertical text stuff, rather than use a `GtkImage` could use a `GtkBox` and apply the image via `background-image` CSS? Then the theme could use `min-height` and `min-width` to show the user pic (and border)

**Comment by blue-devil-93** [comment]
Hi, 
got the color import script for xp themes almost stable. Bad thing is most xp themes obviously didn't insert meaningful colors inside the styles but only used pixmaps. So the pixmap importing script is far more  important.

now for start menu:
Your ideas sounds solid. With this you could implement nearly  all styles in the start menu. 
I would prefer using background-size and a transparent or filled bg _color.GTK box container is the more stable option i agree. Also set the bg position and size insode the css. Just to prevent possible scaling issues.

**Comment by blue-devil-93** [comment]
You could put the text inside of an svg file if i am not mistaken! Text can
be converted to paths inside inkscape too. Ok.

**Comment by rozniak** [comment]
That would fail localisation - no need to worry anyway really I implemented all the above:
![image](https://user-images.githubusercontent.com/13258281/195056040-54358fa1-6bdc-4628-b074-b799abb6090e.png)

**Comment by rozniak** [comment]
Closing old issue, discussion has ran its course
