### ISSUE TITLE
CMake fails to find wintc-shllang despite it being built and installed (Archlinux)

### ISSUE THREAD

**Issue by UmJammerRammy** [rozniak/xfce-winxp-tc#158]
When running `./packplug.sh shell/start` or `./packplug.sh shell/run`, it fails due to not being able to find wintc-shllang, even though its installed and it was able to find wintc-comgtk and wintc-exec. I'm installing everything by following the instructions in issue #88 but those may be outdated by now, im not sure

**Comment by rozniak** [comment]
Have you checked the pkgconfig stuff installed correctly for shllang? That post mentions it's necessary to adjust the pkgconfigdir variable for comgtk and exec, it would also be necessary to do the same for shllang (shllang was developed after that issue was created). I'm pretty sure pkgconfig is how it discovers the lib

**Comment by UmJammerRammy** [comment]
Ah, that seems to be it, should've thought of that haha, its building properly now
