### ISSUE TITLE
Not so much an issue, but a question.

### ISSUE THREAD

**Issue by Greenknight9000** [rozniak/xfce-winxp-tc#165]
Hello! I'm a **very** new user to Linux (moved over as of two days ago) and was very intimidated by all the new looking UI, so I figured this theme would be a good way to settle me in as it'd feel familiar for me to use. Now, I was wondering if you could make a step-by-step tutorial for super newbies such as myself? I managed to copy the git and all that, but the scripts aren't automatically downloaded by the terminal and have to be manually downloaded, when I try and run them it complains of an "Unknown Command" - I use Xubuntu if it's any help!

Sorry if this isn't the right place to post here, still familiarizing myself with GitHub as well. Hahaha

**Comment by rozniak** [comment]
I've thought about maybe making a video tutorial or something, but I am busy with family stuff for this week and next.

Scripts should be present when you clone, the only thing that might not be is the `/submodules` directory contents, if it's empty then do `git submodule update --init --recursive` to ensure it's downloaded.

Could you let me know how you're trying to run the script? You might get that error if you did say `packprog.sh shell/run` instead of `./packprog.sh shell/run`

**Comment by jwcotejr** [comment]
Hi there,

I went ahead and put together a bit of a crude video outlining the installation process as it currently stands on Xubuntu: https://www.youtube.com/watch?v=wKZqrG9GrdI

Let me know what you think!

**Comment by rozniak** [comment]
Thanks @jwcotejr ! I'll check it out when I get time. :grin:

**Comment by rozniak** [comment]
@jwcotejr Nice video - highlights a lot of things to me that I need to resolve, no wonder people find it hard to put together. I did leave a comment but not sure if YouTube has eaten it or not. :cry:

Great job anyway, that faffing with architecture crap should be fixed once I sort out the issue regarding the packaging scripts and such (I didn't know about the `dpkg-architecture` command so I just slapped some bodge into the CMakeLists at the time...)

**Comment by rozniak** [comment]
Build process massively simplified via #192 - new steps documented in README :grin:
