### ISSUE TITLE
Would love to make an Arch AUR package for this.

### ISSUE THREAD

**Issue by weirdbeardgame** [rozniak/xfce-winxp-tc#168]
Heya, I'm just a humble packager whose looking for another interesting challenge.
A couple of questions. Are each of the pieces supposed to be handled like submodules?
Is there anything like a CMake or other build script you use to build it all?

**Comment by rozniak** [comment]
Hey man, sorry it has taken me a bit to get back to you, haven't got any home Internet at the moment (hence the lack of pushes to this repo)

I guess you could consider the components kind of like submodules. The thing is I chose not to use Git submodules for them because I didn't feel like ending up with 100s of repos on my account for potentially tiny things so they're all in here. I have heard (can't remember who I talked to) that this might be a problem for the AUR? I haven't looked into how AUR really works, I suppose if it expects each package to be in its own Git repo it might be a bit stuffed, I figure there must be a way around that or something though?

There is not yet a master build script, and the scripts that *do* exist are tied to Debian (and foolishly, AMD64 without some tweaking in the CMakeLists). It is on my list of things to do, I'm just not sure when I will get to that is the thing, I keep thinking after I'm done with #13, maybe.

**Comment by rozniak** [comment]
#140  is in progress

**Comment by weirdbeardgame** [comment]
Sweet! I'll keep an eye on it and get something cooking on my end when it's done :)

**Comment by rozniak** [comment]
AUR package available now following #140 #182 and #190
