### ISSUE TITLE
Unable to run wintc-taskband

### ISSUE THREAD

**Issue by UmJammerRammy** [rozniak/xfce-winxp-tc#191]
Trying to install this theme on fedora and I've managed to get everything built and installed, but now trying to launch wintc-taskband just throws me this
```
** (wintc-taskband:4607): CRITICAL **: 14:46:46.475: Failed to open libgdk for symbols.
** (wintc-taskband:4607): CRITICAL **: 14:46:46.475: Failed to resolve display protocol APIs.
Segmentation fault (core dumped)
``` 
Not sure what to do about it, can't find any info on this error anywhere

**Comment by UmJammerRammy** [comment]
Alternatively any sort of help just getting these packages to build on fedora would be appreciated, currently I'm using packages built in a debian vm because it was the only way i could manage to make it work, but if i could get these to compile with cmake in fedora that would be nice

**Comment by UmJammerRammy** [comment]
Managed to fix it, needed garcon-devel and libwnck3-devel

**Comment by rozniak** [comment]
@UmJammerRammy Sorry it's a bit of a pain atm - basically I made `wintc-taskband` load libraries related to the display protocol at runtime so that when XFCE has its Wayland port completed one day, the shell will immediately work. Trouble is with the dependencies, since I don't think there is a way to do an 'either/or' thing for packages (either `libxfce4windowing` or `libwnck`)...

> Alternatively any sort of help just getting these packages to build on fedora would be appreciated, currently I'm using packages built in a debian vm because it was the only way i could manage to make it work, but if i could get these to compile with cmake in fedora that would be nice

I did have Red Hat on my list of packaging formats to sort out, I had it in mind to look into packaging formats once more is complete (desktop, basic explorer, logonui, boot screen). In the meantime the components can be compiled with no packaging format pretty much just like any other CMake project, other than needing to provide `-DWINTC_SKU` (eg. `-DWINTC_SKU=xpclient-pro`).

If you get stuck I'm always happy to help here, was just away this weekend otherwise I would've replied.
