### ISSUE TITLE
Build fails on Linux Mint

### ISSUE THREAD

**Issue by j-osborne** [rozniak/xfce-winxp-tc#207]
![image](https://github.com/rozniak/xfce-winxp-tc/assets/141033063/940e3c11-4b27-4dc7-b91a-46f75a32b727)

Build fails on linux mint, all dependencies present as confirmed by chkdeps.

**Comment by rozniak** [comment]
I guess I assumed the repo would always be cloned... you'll want `git` installed so the build tag stuff can work.

Aside from that, what version of `cmake` is that? (use `cmake --version`)

**Comment by rozniak** [comment]
Is 3.22 the latest on there? I can work around it since the `--fresh` parameter just bins some cached stuff (added in 3.24). 3.22 is quite old though, even Debian 11 seemed to have it! :stuck_out_tongue:

**Comment by j-osborne** [comment]
![image](https://github.com/rozniak/xfce-winxp-tc/assets/141033063/daede3f9-92f4-4af8-a370-b6c87b12313b)

Latest version of cmake on the ubuntu repos that Mint uses, without enabling snap. Ubuntu stopped pushing new version that aren't using snap so I think Mint uses a debian 11 fallback, which is 3.22  (Thanks Mint XD)

**Comment by rozniak** [comment]
I am so confused how this has occurred because I wrote this when I was on Debian 11, and in fact just tested Debian 11 for a different issue and never had `cmake` complain about `--fresh`! :dizzy_face: 

Not to worry, I will just clear with `rm` first, no loss because there were some other issues with CMake not detecting changes properly so it basically always does a clean build anyway.

**Comment by rozniak** [comment]
`--fresh` param removed
