### ISSUE TITLE
Thank you.

### ISSUE THREAD

**Issue by Whistrock** [rozniak/xfce-winxp-tc#345]
Thank you so much for making all of this a real thing. There are no old/skeuomorphic(ish) themes nowadays let alone Windows related themes that _also_ aim for pixel-perfect accuracy (this might be the only one, lol). I dislike modern flat corporate looking interfaces and this project specifically scratches the itch for me. I've been silently following and using themes of this project for the past two or so years. I've just happened to create a Github account today and I've always felt the need to thank you, so, here it is. Thank you. Love you. Take your time and take good care.

**Comment by orwellianpenguin** [comment]
Please tell us how to install it lmao they still haven't made an installation guide

**Comment by AlphaNERD-** [comment]
@orwellianpenguin Do you happen to run Ubuntu or another debian based distro? Because i‘m trying to follow the instructions to build a deb package and i cannot install the missing dependencies. After burying a bit in the repo i think i‘m starting to see the problem: chkdeps.sh is outputting the wrong package names. The file debmaps contains packages that i can actually find in the package manager.

I‘m torturing my little MX Linux netbook with a broken fan with VS Code as we speak to find out more.

**Comment by rozniak** [comment]
@Whistrock I appreciate it man, I'm glad you like it. :grin: 

@orwellianpenguin @AlphaNERD- Can you open a separate issue for MX Linux ? I thought it was dpkg I guess not.

**Comment by AlphaNERD-** [comment]
@rozniak Created issue #346 as requested.
